### ISSUE TITLE
quartz-wm

### ISSUE THREAD

**Issue by Futi7** [XQuartz/quartz-wm#10]
I dont know what is the exact problem but i will try to explain.I installed Visual Studio Code for C Sharp coding.I think i broke whole X11 and XQuartz systems completely while i was installing Homebrew and Node.js .Now when i try to open a wineskin app it gives me xquartz-wm or X11 or wineskin Error.I tried to reinstalling XQuartz but it was useless.

**Comment by jeremyhu** [comment]
The Wineskin bug is a bug in XQuartz (which Wineskin uses), but it should only be triggered when encountering another error.

Your quartz-wm-ws bug seems to be because of an installation issue with Age of Empires II HD.app.  That's likely the reason why WineskinX11 is exiting (and tripping over the atexit bug)

**Comment by Futi7** [comment]
I know it seems like a problem with app but it affected all Wineskin apps
