### ISSUE TITLE
Multi monitor can cause windows to get lost

### ISSUE THREAD

**Issue by pantoss** [XQuartz/quartz-wm#12]
Mac OS X 10.13.4
Mac Book Pro with Cinema display
Displays have separate spaces

Some applications when they start will move their window to a position which is out of reach of any of the screens. I haven't found a way to resolve this other than trying to grab the window before the application decides to move it.

Applications which do this. Clion and Sqldeveloper.

**Comment by KenThomases** [comment]
I've seen something similar happen in a different context (with Cocoa). In that case, there were two windows in a Cocoa parent-child relationship. That's roughly the transient-for relationship in X. If the child window is programmatically repositioned, it's still assigned to the same Space as the parent, even if it's moved to another screen. With "Displays have separate Spaces" enabled, that means it's invisible (because windows are clipped to their Space's screen).

The solution in that case was to temporarily break the parent-child relationship when either is moved in a way that puts them on separate screens (iff "Displays have separate Spaces" is enabled) and restore it when they are moved back to the same screen.

Do you know if these windows are transient-for another window? In particular, are they always in front of some other window?

**Comment by pantoss** [comment]
I don’t think so. It is the main window but there is a splash screen show before hand. I don’t see how that might effect thing.

Another very odd thing is the background on the model and some contextual menus are rendered black on my second monitor. Don’t know how that might help.

**Comment by M1sf3t** [comment]
this happens with inkscape as well, its same issue as the one you mentioned with Cocoa, on start up its just moving the window to where it was last positioned, which is out of view if you happen to have previously moved it to the second display.  

Kinda surprised not to see more mentions of it here.  On ink you can disable a setting to make the original window not return to its original position but it doesn't work for all the pop up panels.   There are half a dozen work arounds, but the simpliest thing to do is just disable the macs setting for separate desktops altogether.  At least until it becomes a habit of returning them to the desktop the will first appear on before you exit.

**Comment by jeremyhu** [comment]
Can you please file this at http://bugreport.apple.com if the issue exists with Big Sur still?  This doesn't seem quartz-wm related.  Please also refernce the FB number, so I can evangelize it.
